### ISSUE TITLE
Problems with using mute on multiple player selectors

### ISSUE THREAD

**Issue by ApplecakeYT** [Declipsonator/Chat-Control#10]
Using `/mute permanent @a` successfully mutes all online players however attempting to unmute all players similarly or by using `execute as @a run unmute @s` (unsure of the actual command), outputs that the unmutes were successful however players were still not able to send messages.

**Comment by Declipsonator** [comment]
Hey, I pushed a new commit with an update to 1.20.1 and a bunch of other stuff right before this. I tested it out and can't seem to replicate the issue with the following commands:
```
/mute permanent @a
/mute remove @a
```
I'll release the update on modrinth and curseforge soon. I'm going to close this for now but if you still run into the issue just comment and I'll reopen it. 👍

**Comment by ApplecakeYT** [comment]
Is it possible to also apply this to the 1.19.4 release?

**Comment by Declipsonator** [comment]
Yeah, I can try

**Comment by Declipsonator** [comment]
I released it on modrinth and it'll be available on curseforge soon
