### ISSUE TITLE
Release Version doesn't match title

### ISSUE THREAD

**Issue by ApplecakeYT** [Declipsonator/Chat-Control#11]
![image](https://github.com/Declipsonator/Chat-Control/assets/69206573/3aa994f9-c001-4779-b2f0-2566036b0af3)

Not sure if its intentional but the release file for Chat Control 1.3 - 1.19.4 says 1.25 instead of 1.3

File Name: `chat-control-1.25.jar`

**Comment by Declipsonator** [comment]
Oh yeah, I just did that to make sure I was uploading the right version for 1.19.4. I can fix that to get rid of any confusion
