### ISSUE TITLE
Priority setting? Use with Discord Integration

### ISSUE THREAD

**Issue by SmallSansSerif** [Declipsonator/Chat-Control#13]
I'm trying to use this with Discord Integraton mod too to get the in-game chat onto Discord. It filters in game fine as expected but the unfiltered chat gets sent to Discord. Is there a way that the priority can be changed to make this work?

**Comment by Declipsonator** [comment]
Can you send the github link of the mod you use for discord integration?

**Comment by SmallSansSerif** [comment]
Thanks! Here you go.

https://github.com/ErdbeerbaerLP/Discord-Integration-Fabric
https://modrinth.com/plugin/dcintegration
https://modrinth.com/plugin/dcintegration/versions

**Comment by SmallSansSerif** [comment]
Any way to get a back port to 1.20.1? I've got a Cobblemon server and need that version.

**Comment by Declipsonator** [comment]
https://modrinth.com/mod/chat/version/xzE8rQh3
