### ISSUE TITLE
Any way to disable "I RAN"?

### ISSUE THREAD

**Issue by Gamestudiox-t3ryo** [Declipsonator/Chat-Control#14]
Hi, is there any way to disable Chat Control from writing the "I RAN" command to the console? We have a login on the server and it is not nice when the mod prints out the passwords of each player.
Thanks in advance for the answer
![image](https://github.com/Declipsonator/Chat-Control/assets/147524465/f3d5de0d-e3bd-4c79-b0e9-64f2f04aa355)

**Comment by Declipsonator** [comment]
Oops - My mistake, I meant to remove that after debugging but didn't notice. Thanks for notifying me!

**Comment by Declipsonator** [comment]
https://modrinth.com/mod/chat/version/1.4.1
https://modrinth.com/mod/chat/version/T3XIFhtV

**Comment by Gamestudiox-t3ryo** [comment]
Okay. And do you know why the mod is not blocking the words/phrases/etc... and players can still send it? Or mute, that also doesn't work and player can still send messages without problem. Server specs.: Fabric 1.20.1 0.15.11/ Mod version: 1.4

**Comment by Declipsonator** [comment]
I can't replicate that on 1.20.1 with the version I sent. Can you make sure the mod is installed and if it is send the game log.
