### ISSUE TITLE
Mute/phrases-words blocking doesn't work

### ISSUE THREAD

**Issue by Gamestudiox-t3ryo** [Declipsonator/Chat-Control#15]
The mod is not blocking the words/phrases/etc... and players can still send it. Or mute, that also doesn't work and player can still send messages without problem. 
Server specs.: Fabric 1.20.1 0.15.11/ Mod version: 1.4

**Comment by Declipsonator** [comment]
I can't replicate that on 1.20.1 with the version I sent. Can you make sure the mod is installed and if it is send the game log.

**Comment by Gamestudiox-t3ryo** [comment]
In the new version, it is working
