### ISSUE TITLE
Translatable text

### ISSUE THREAD

**Issue by xllifi** [Declipsonator/Chat-Control#18]
Make the mod's text translatable! Most mods (e.g. GOML, Item Obliterator) provide support for languages in a vanilla-friendly way. Translations are stored in `assets` and/or `data` folder so they can be modified with a resource/data pack.

**Comment by Declipsonator** [comment]
Translations are stored in `data/chat-control/lang/en_us.json` as of 519af30. I also included a library that shifts translations to the server so the clients do not need the mod. One thing though - the new version will not be available < 1.21 due to conflicts.
Cheers!
