### ISSUE TITLE
[ Feature request ]: Add starting word list of common profanity

### ISSUE THREAD

**Issue by Silverdev2482** [Declipsonator/Chat-Control#19]
I think a starting word list of common profanity would be nice, as it would mean you don't need to configure as much starting off, and people may figure how to get around a more basic list, but it would be 90% of what servers whose players aren't trying to bypass it need to be configured.

**Comment by Declipsonator** [comment]
Just built [this website](https://jacksonhickey.tech/Chat-Control-Config-Gen/) for this issue!
