### ISSUE TITLE
Adding this seems to break the World Edit mod, no console errors.

### ISSUE THREAD

**Issue by NotPhoenic** [Declipsonator/Chat-Control#23]
I don't have any useful information, unfortunately, but still adding an issue just in case.

**Comment by Declipsonator** [comment]
What version of minecraft are you using?

**Comment by NotPhoenic** [comment]
> What version of minecraft are you using?

I am using 1.21, in the mean time I have found out that only the chat commands seem to be broken, ex., If I do //wand, nothing happens, but I can get a wooden axe from creative and it will still let me make selections. I assume this mod is somehow preventing the world edit mod commands from working.

Mods; 
Axiom-3.1.0-for-MC1.21
chat-control-1.6
fabric-api-0.100.4+1.21
worldedit-mod-7.3.6

**Comment by Declipsonator** [comment]
Update Chat Control to [1.6.1](https://modrinth.com/mod/chat/version/1.6.1)

**Comment by NotPhoenic** [comment]
You may want to add 1.6.1 to your featured versions on modrinth, thanks!
