### ISSUE TITLE
[feature request] ignore filtered message

### ISSUE THREAD

**Issue by Magicrafter13** [Declipsonator/Chat-Control#9]
2 things, but here's the main idea:
- a boolean that, if true, will completely drop the chat message instead of replacing anything (as if the user had never even tried to send it)

secondarily to that:
- the ability to react to messages matching the filter, by running a user specified command (this could be used, for example, to `tellraw` the offending player, and give them some kind of "please don't say that" message)

I don't know anything about Minecraft modding so perhaps the second one is hard, but I imagine the first one would be pretty simple to do.

**Comment by Declipsonator** [comment]
I've implemented both but I think you were somewhat mistaken by the first suggestion. I believe you were thinking of the replacement letters which is just made to prevent people from bypassing the filter by replacing letters before filtering the message. For example:
```
Word to filter: first
Message Sent: f1rst
replace 1 with i: first
filtered
```

But censoring and still sending it seemed cool so I added a new setting called censorAndSend which censors the message and then sends it but it is off by default.


Also I added responses to messages to just make it more intuitive.
